(() => {
'use strict';
const DEFAULTS=[
 {id:'whatsapp',name:'WhatsApp',enabled:true,kind:'coordination',number:'',holder:'',instructions:'Coordina el pago y la entrega directamente con nuestro equipo.',qr:''},
 {id:'yape',name:'Yape',enabled:false,kind:'qr',number:'',holder:'SADI PERÚ',instructions:'Escanea el QR y envía el comprobante por WhatsApp.',qr:''},
 {id:'plin',name:'Plin',enabled:false,kind:'qr',number:'',holder:'SADI PERÚ',instructions:'Escanea el QR y confirma el pago por WhatsApp.',qr:''},
 {id:'transferencia',name:'Transferencia bancaria',enabled:false,kind:'bank',number:'',holder:'',instructions:'Realiza la transferencia y envía el comprobante por WhatsApp.',qr:''}
];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function methods(){const raw=state?.settings?.paymentMethods;return Array.isArray(raw)&&raw.length?raw.map((x,i)=>({...DEFAULTS[i]||DEFAULTS[0],...x,id:x.id||DEFAULTS[i]?.id||('method'+i)})):DEFAULTS.map(x=>({...x}));}
function ensureSettingsUI(){
 const form=$('#admin-settings .admin-form'); if(!form||$('#paymentAdminGrid'))return;
 const anchor=[...form.querySelectorAll('.section-label')].find(x=>/portada/i.test(x.textContent||''));
 const block=document.createElement('div');block.className='form-group full';block.innerHTML=`<div class="section-label">Formas de pago y códigos QR</div><div class="admin-alert"><b>Administrable:</b> activa o desactiva medios de pago, cambia números, titulares, instrucciones y QR. Los cambios aparecerán automáticamente en el carrito.</div><div class="payment-admin-grid" id="paymentAdminGrid"></div>`;
 if(anchor)anchor.parentElement.insertBefore(block,anchor);else form.prepend(block);
 renderPaymentAdmin();
}
function renderPaymentAdmin(){const grid=$('#paymentAdminGrid');if(!grid)return;grid.innerHTML=methods().map((m,i)=>`<article class="payment-admin-card ${m.enabled?'':'is-disabled'}" data-payment-index="${i}"><div class="payment-admin-head"><strong>${esc(m.name)}</strong><label><input type="checkbox" class="pay-enabled" ${m.enabled?'checked':''}> Activo</label></div><div class="form-group"><label>Nombre visible</label><input class="field pay-name" value="${esc(m.name)}"></div><div class="form-group"><label>Número, cuenta o CCI</label><input class="field pay-number" value="${esc(m.number||'')}"></div><div class="form-group"><label>Titular</label><input class="field pay-holder" value="${esc(m.holder||'')}"></div><div class="form-group"><label>Instrucciones para el cliente</label><textarea class="textarea pay-instructions">${esc(m.instructions||'')}</textarea></div><div class="payment-admin-qr"><img class="pay-qr-preview" src="${esc(m.qr||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22120%22 height=%22120%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22white%22/%3E%3Ctext x=%2250%25%22 y=%2250%25%22 dominant-baseline=%22middle%22 text-anchor=%22middle%22 font-size=%2212%22 fill=%22%23666%22%3ESin QR%3C/text%3E%3C/svg%3E')}"><div><label class="btn btn-secondary btn-sm">Subir QR<input hidden type="file" accept="image/*" class="pay-qr-file"></label><button type="button" class="btn btn-danger btn-sm pay-remove-qr">Quitar QR</button><input type="hidden" class="pay-qr-data" value="${esc(m.qr||'')}"><small class="muted" style="display:block;margin-top:8px">PNG o JPG. Se comprime automáticamente.</small></div></div></article>`).join('');
 grid.querySelectorAll('.pay-enabled').forEach(x=>x.onchange=()=>x.closest('.payment-admin-card').classList.toggle('is-disabled',!x.checked));
 grid.querySelectorAll('.pay-remove-qr').forEach(x=>x.onclick=()=>{const c=x.closest('.payment-admin-card');c.querySelector('.pay-qr-data').value='';c.querySelector('.pay-qr-preview').src='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22120%22 height=%22120%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22white%22/%3E%3Ctext x=%2250%25%22 y=%2250%25%22 dominant-baseline=%22middle%22 text-anchor=%22middle%22 font-size=%2212%22 fill=%22%23666%22%3ESin QR%3C/text%3E%3C/svg%3E'});
 grid.querySelectorAll('.pay-qr-file').forEach(input=>input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const data=await compressQr(file);const c=input.closest('.payment-admin-card');c.querySelector('.pay-qr-data').value=data;c.querySelector('.pay-qr-preview').src=data;showToast('QR preparado. Pulsa Guardar configuración.')}catch(e){showToast('No se pudo procesar el QR: '+e.message)}});
}
function compressQr(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('El archivo no es una imagen.'));const r=new FileReader();r.onerror=()=>reject(new Error('No se pudo leer el archivo.'));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Imagen inválida.'));img.onload=()=>{const size=520,c=document.createElement('canvas');c.width=size;c.height=size;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);const ratio=Math.min(size/img.width,size/img.height);const w=img.width*ratio,h=img.height*ratio;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);resolve(c.toDataURL('image/jpeg',.88))};img.src=r.result};r.readAsDataURL(file)});}
function collectMethods(){return [...document.querySelectorAll('.payment-admin-card')].map((c,i)=>({id:methods()[i]?.id||('method'+i),kind:methods()[i]?.kind||'qr',enabled:c.querySelector('.pay-enabled').checked,name:c.querySelector('.pay-name').value.trim()||'Pago',number:c.querySelector('.pay-number').value.trim(),holder:c.querySelector('.pay-holder').value.trim(),instructions:c.querySelector('.pay-instructions').value.trim(),qr:c.querySelector('.pay-qr-data').value||''}));}
function renderCheckoutPayments(){const old=$('.pay-grid');if(!old)return;const active=methods().filter(x=>x.enabled!==false);old.className='payment-checkout-grid';old.innerHTML=active.map((m,i)=>`<div class="payment-checkout-card ${i===0?'active':''}" data-pay-id="${esc(m.id)}" onclick="selectPaymentV31('${esc(m.id)}',this)"><strong>${esc(m.name)}</strong><p>${esc(m.instructions||'Selecciona este método de pago.')}</p></div>`).join('');let detail=$('#paymentDetailV31');if(!detail){detail=document.createElement('div');detail.id='paymentDetailV31';detail.className='payment-detail-box hidden';old.after(detail)}if(active.length){state.payment=active[0].name;showPaymentDetail(active[0]);}}
function showPaymentDetail(m){const box=$('#paymentDetailV31');if(!box)return;if(m.kind==='coordination'&&!m.qr&&!m.number){box.classList.add('hidden');box.innerHTML='';return;}box.classList.remove('hidden');box.innerHTML=`${m.qr?`<img src="${esc(m.qr)}" alt="QR ${esc(m.name)}">`:'<div></div>'}<div class="payment-detail-copy"><b>${esc(m.name)}</b>${m.number?`<span class="payment-number">${esc(m.number)}</span>`:''}${m.holder?`<span>Titular: ${esc(m.holder)}</span>`:''}<small>${esc(m.instructions||'')}</small></div>`;}
window.selectPaymentV31=function(id,el){const m=methods().find(x=>x.id===id);if(!m)return;state.payment=m.name;document.querySelectorAll('.payment-checkout-card').forEach(x=>x.classList.remove('active'));el?.classList.add('active');showPaymentDetail(m)};
const oldOpen=window.openCheckout;window.openCheckout=function(){const result=oldOpen.apply(this,arguments);setTimeout(renderCheckoutPayments,0);return result};
const oldRender=window.renderSettings;window.renderSettings=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{ensureSettingsUI();renderPaymentAdmin()},0);return r};
const oldSave=window.saveSettings;window.saveSettings=async function(){ensureSettingsUI();state.settings.paymentMethods=collectMethods();const result=await oldSave.apply(this,arguments);renderCheckoutPayments();return result};
const oldApply=window.applySettings;window.applySettings=function(){const r=oldApply.apply(this,arguments);return r};
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{ensureSettingsUI();if($('#checkoutModal'))renderCheckoutPayments()},900));
})();