(() => {
'use strict';
const OWNER_UID='sr7PqTYzkySBndnmFDcaVz8v6Iz2';
const MODULES=[
 ['dashboard','Panel principal','Resumen general del negocio'],['orders','Pedidos','Ver y gestionar pedidos'],['sales','Ventas','Consultar ventas y resultados'],['payments','Pagos','Confirmar y revisar pagos'],['clients','Clientes','Consultar datos de clientes'],['catalog','Catálogo','Crear y editar productos y categorías'],['inventory','Inventario','Modificar existencias y movimientos'],['gallery','Galería','Administrar imágenes y videos'],['promotions','Promociones','Crear descuentos y campañas'],['shipping','Envíos','Configurar y gestionar entregas'],['messages','Mensajes','Leer y responder consultas'],['reviews','Opiniones','Moderar reseñas'],['reports','Reportes','Consultar reportes internos'],['settings','Configuración','Cambiar marca, pagos y ajustes'],['users','Usuarios y seguridad','Administrar accesos y roles']
];
const ROLE_DEFAULTS={
 'Administrador':['*'],
 'Ventas':['dashboard','orders','clients','sales','payments','shipping','messages'],
 'Inventario':['dashboard','catalog','inventory','orders'],
 'Contenido':['dashboard','catalog','gallery','promotions'],
 'Atención al cliente':['dashboard','orders','clients','messages','reviews'],
 'Personalizado':[]
};
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date().toISOString();
let auditRows=[];let auditLoading=false;
function owner(){return window._auth?.currentUser?.uid===OWNER_UID}
function securityAdmin(){return owner()||window._firebasePermissions?.includes('*')}
function status(msg,error=false){const e=$('#userSaveStatus');if(e){e.textContent=msg;e.dataset.type=error?'error':'ok'}if(typeof showToast==='function')showToast(msg)}
function normalizePermissions(v){return Array.isArray(v)?[...new Set(v.filter(Boolean))]:[]}
function userById(id){return (state.users||[]).find(x=>x.id===id||x.uid===id)}
function permissionLabel(k){return MODULES.find(x=>x[0]===k)?.[1]||k}
function selectedPermissions(){return [...document.querySelectorAll('#userPermissionGrid input[data-permission]:checked')].map(x=>x.dataset.permission)}
function strongPassword(v){return v.length>=10&&/[a-z]/.test(v)&&/[A-Z]/.test(v)&&/\d/.test(v)&&/[^A-Za-z0-9]/.test(v)}
function auditId(){return 'audit_'+Date.now()+'_'+Math.random().toString(36).slice(2,9)}
function safeSnapshot(u){if(!u)return null;return {uid:u.uid||'',name:u.name||'',email:u.email||'',role:u.role||'',active:u.active!==false,permissions:normalizePermissions(u.permissions)}}
function diff(before,after){const out=[];if(!before)return ['Usuario creado'];if(!after)return ['Acceso eliminado'];if(before.name!==after.name)out.push('Nombre actualizado');if(before.role!==after.role)out.push(`Rol: ${before.role||'-'} → ${after.role||'-'}`);if(before.active!==after.active)out.push(after.active?'Acceso activado':'Acceso desactivado');const a=normalizePermissions(before.permissions).sort().join('|'),b=normalizePermissions(after.permissions).sort().join('|');if(a!==b)out.push('Permisos modificados');return out.length?out:['Datos actualizados']}
function actionFor(before,after){if(!before)return 'CREATE';if(!after)return 'DELETE';if(before.active!==after.active)return 'STATUS_CHANGE';if(before.role!==after.role)return 'ROLE_CHANGE';if(normalizePermissions(before.permissions).sort().join('|')!==normalizePermissions(after.permissions).sort().join('|'))return 'PERMISSIONS_CHANGE';return 'UPDATE'}
function makeAudit(target,before,after,reason){const actor=window._auth?.currentUser;return {id:auditId(),action:actionFor(before,after),targetId:target.id||target.uid||target.email,targetUid:target.uid||'',targetName:target.name||'',targetEmail:target.email||'',actorUid:actor?.uid||'',actorEmail:actor?.email||'',reason:reason||'Sin motivo indicado',before:safeSnapshot(before),after:safeSnapshot(after),changes:diff(before,after),createdAt:now(),serverCreatedAt:window._fb.serverTimestamp()}}
function renderPermissionGrid(role,perms){const box=$('#userPermissionGrid');if(!box)return;const isCustom=role==='Personalizado',isOwner=owner();box.innerHTML=MODULES.map(([key,title,desc])=>{const checked=perms.includes('*')||perms.includes(key);const privileged=key==='users';const locked=!isCustom||(!isOwner&&privileged);return `<label class="${checked?'selected ':''}${locked?'locked':''}"><input type="checkbox" data-permission="${key}" ${checked?'checked':''} ${locked?'disabled':''}><span><b>${esc(title)}${privileged?' · sensible':''}</b><small>${esc(desc)}</small></span></label>`}).join('');box.querySelectorAll('input').forEach(i=>i.addEventListener('change',()=>i.closest('label').classList.toggle('selected',i.checked)));const help=$('#permissionHelp');if(help)help.textContent=isCustom?'Modo personalizado activo: marca únicamente las funciones necesarias.':'El rol aplica permisos recomendados automáticamente. Elige “Personalizado” para modificarlos.'}
window.syncRolePermissions=function(){const role=$('#userRole')?.value||'Ventas';if(role==='Administrador'&&!owner()){status('Solo la cuenta propietaria puede otorgar Control total.',true);$('#userRole').value='Ventas';return renderPermissionGrid('Ventas',ROLE_DEFAULTS.Ventas)}renderPermissionGrid(role,ROLE_DEFAULTS[role]||[])};
window.selectAllCustomPermissions=function(){if($('#userRole')?.value!=='Personalizado')return status('Selecciona el rol Personalizado para editar permisos.',true);document.querySelectorAll('#userPermissionGrid input:not(:disabled)').forEach(i=>{i.checked=true;i.closest('label').classList.add('selected')})};
window.clearCustomPermissions=function(){if($('#userRole')?.value!=='Personalizado')return status('Selecciona el rol Personalizado para editar permisos.',true);document.querySelectorAll('#userPermissionGrid input:not(:disabled)').forEach(i=>{i.checked=false;i.closest('label').classList.remove('selected')})};
window.openUserForm=function(id=''){if(!securityAdmin())return status('No tienes autorización para administrar usuarios.',true);const u=userById(id)||{};$('#userId').value=u.id||'';$('#userName').value=u.name||'';$('#userEmail').value=u.email||'';$('#userEmail').disabled=!!u.id;$('#userPassword').value='';$('#userPasswordGroup').style.display=u.id?'none':'';let role=u.role||'Ventas';if(role==='Administrador'&&!owner())role='Ventas';$('#userRole').value=role;[...$('#userRole').options].forEach(o=>{if(o.value==='Administrador')o.disabled=!owner()});$('#userActive').value=String(u.active!==false);$('#userChangeReason').value='';$('#userSecurityConfirm').checked=false;$('#userModalTitle').textContent=u.id?'EDITAR USUARIO Y SEGURIDAD':'AGREGAR USUARIO SEGURO';$('#userSaveStatus').textContent='';renderPermissionGrid(role,normalizePermissions(u.permissions).length?normalizePermissions(u.permissions):(ROLE_DEFAULTS[role]||[]));openModal('userModal')};
async function atomicUserChange(type,ref,record,audit){const batch=window._fb.writeBatch(window._db);if(type==='delete')batch.delete(ref);else if(type==='update')batch.set(ref,record,{merge:true});else batch.set(ref,record);batch.set(window._fb.doc(window._db,'sadi_user_audit',audit.id),audit);await batch.commit()}
window.saveSystemUser=async function(){
 const btn=$('#saveUserBtn');if(btn?.dataset.busy==='1')return;if(!securityAdmin())return status('No tienes autorización para administrar usuarios.',true);
 const id=$('#userId').value.trim(),name=$('#userName').value.trim(),email=$('#userEmail').value.trim().toLowerCase(),pass=$('#userPassword').value,role=$('#userRole').value,active=$('#userActive').value==='true',reason=$('#userChangeReason').value.trim();
 if(!name||!email)return status('Completa nombre y correo.',true);if(email===String(window._auth?.currentUser?.email||'').toLowerCase())return status('No puedes crear o modificar tu propia cuenta desde esta pantalla.',true);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return status('Escribe un correo válido.',true);if(!id&&!strongPassword(pass))return status('La contraseña debe tener 10 caracteres, mayúscula, minúscula, número y símbolo.',true);if(!reason)return status('Indica el motivo del cambio para el historial.',true);if(!$('#userSecurityConfirm').checked)return status('Confirma que revisaste el rol y los permisos.',true);if(role==='Administrador'&&!owner())return status('Solo el propietario puede otorgar Control total.',true);
 let permissions=role==='Personalizado'?selectedPermissions():(ROLE_DEFAULTS[role]||[]);if(role==='Personalizado'&&!permissions.length)return status('Selecciona al menos un permiso para el rol Personalizado.',true);if(!owner()&&(permissions.includes('*')||permissions.includes('users')))return status('No puedes otorgar permisos de seguridad elevados.',true);
 btn.dataset.busy='1';btn.disabled=true;status(id?'Actualizando usuario y registrando historial...':'Creando usuario seguro...');let secondary=null,docId=id,uidValue=id,authCreated=false;
 try{
  if(!id){try{secondary=window._firebaseInitializeApp(window._firebaseConfig,'sadi-secure-'+Date.now());const sa=window._firebaseGetAuth(secondary);const cred=await window._fb.createUserWithEmailAndPassword(sa,email,pass);uidValue=cred.user.uid;docId=uidValue;authCreated=true;await window._fb.signOut(sa)}catch(e){if(e?.code==='auth/email-already-in-use'){docId=email;uidValue=''}else throw e}finally{if(secondary)await window._firebaseDeleteApp(secondary).catch(()=>{})}}
  const before=id?safeSnapshot(userById(id)):null,previous=userById(id)||{};if(!owner()&&(previous.role==='Administrador'||normalizePermissions(previous.permissions).includes('*')))throw new Error('Esta cuenta privilegiada solo puede ser modificada por el propietario.');if(previous.uid===window._auth?.currentUser?.uid)throw new Error('No puedes modificar tu propio acceso desde esta pantalla.');
  const record={id:docId,uid:uidValue||previous.uid||'',name,email,role,active,enabled:active,permissions,securityVersion:2,updatedAt:now(),updatedBy:window._auth.currentUser.uid,createdAt:previous.createdAt||now(),createdBy:previous.createdBy||window._auth.currentUser.uid};
  const audit=makeAudit(record,before,record,reason);await atomicUserChange(id?'update':'create',window._fb.doc(window._db,'sadi_users',docId),record,audit);status('Usuario, rol, permisos e historial guardados correctamente.');await window.syncUsersFromFirestore(false);await window.loadUserAudit(false);setTimeout(()=>closeModal('userModal'),550);if(authCreated)showToast('Cuenta creada con seguridad reforzada.')
 }catch(e){console.error(e);status('NO SE GUARDÓ: '+(e.message||'Error desconocido.'),true)}finally{btn.disabled=false;delete btn.dataset.busy}
};
window.toggleSystemUser=async function(id){const u=userById(id);if(!u)return;if(u.uid===OWNER_UID||u.uid===window._auth?.currentUser?.uid)return status('Esta cuenta está protegida y no puede cambiarse aquí.',true);if(!owner()&&(u.role==='Administrador'||normalizePermissions(u.permissions).includes('*')))return status('Solo el propietario puede modificar una cuenta privilegiada.',true);const next=u.active===false,reason=prompt(next?'Motivo para activar el acceso:':'Motivo para desactivar el acceso:');if(!reason?.trim())return;const after={...u,active:next,enabled:next,updatedAt:now(),updatedBy:window._auth.currentUser.uid};try{await atomicUserChange('update',window._fb.doc(window._db,'sadi_users',id),after,makeAudit(after,u,after,reason.trim()));status(next?'Usuario activado y registrado en historial.':'Usuario desactivado y registrado en historial.');await window.syncUsersFromFirestore(false);await window.loadUserAudit(false)}catch(e){status('NO SE CAMBIÓ: '+e.message,true)}};
window.deleteSystemUser=async function(id){const u=userById(id);if(!u)return;if(u.uid===OWNER_UID||u.uid===window._auth?.currentUser?.uid)return status('Esta cuenta está protegida.',true);if(!owner()&&(u.role==='Administrador'||normalizePermissions(u.permissions).includes('*')))return status('Solo el propietario puede eliminar una cuenta privilegiada.',true);const reason=prompt('Escribe el motivo para eliminar el acceso:');if(!reason?.trim()||!confirm(`¿Eliminar el acceso de ${u.name}? El historial se conservará.`))return;try{await atomicUserChange('delete',window._fb.doc(window._db,'sadi_users',id),null,makeAudit(u,u,null,reason.trim()));status('Acceso eliminado. El historial quedó conservado.');await window.syncUsersFromFirestore(false);await window.loadUserAudit(false)}catch(e){status('NO SE ELIMINÓ: '+e.message,true)}};
window.renderUsers=function(){const box=$('#usersList');if(!box)return;const users=(state.users||[]).filter(u=>u.uid!==OWNER_UID&&u.id!==OWNER_UID);box.innerHTML=users.length?users.map(u=>{const p=normalizePermissions(u.permissions),priv=u.role==='Administrador'||p.includes('*');return `<article class="v41-user-card"><div class="v41-user-main"><div><b>${esc(u.name)}</b><div class="muted">${esc(u.email||'Sin correo')}</div><div class="v41-user-meta"><span class="v41-badge">${esc(u.role||'Empleado')}</span><span class="v41-badge ${u.active!==false?'on':'off'}">${u.active!==false?'ACTIVO':'DESHABILITADO'}</span>${priv?'<span class="v41-badge user-security-warning">PRIVILEGIADO</span>':''}</div><div class="v41-perms">${p.includes('*')?'Control total':p.map(permissionLabel).join(' · ')||'Sin permisos'}</div></div></div><div class="v41-user-actions"><button class="btn btn-secondary btn-sm" onclick="openUserForm('${esc(u.id)}')">Editar seguridad</button><button class="btn btn-secondary btn-sm" onclick="toggleSystemUser('${esc(u.id)}')">${u.active!==false?'Deshabilitar':'Activar'}</button><button class="btn btn-danger btn-sm" onclick="deleteSystemUser('${esc(u.id)}')">Eliminar acceso</button></div></article>`}).join(''):'<div class="empty">No hay usuarios adicionales.</div>'};
window.loadUserAudit=async function(show=true){const box=$('#userAuditList');if(!box||auditLoading)return;if(!window._firebaseReady)return box.innerHTML='<div class="audit-empty">Firebase no está disponible.</div>';auditLoading=true;try{const request=window._fb.getDocs(window._fb.collection(window._db,'sadi_user_audit'));const snap=await Promise.race([request,new Promise((_,reject)=>setTimeout(()=>reject(new Error('La carga del historial tardó demasiado.')),12000))]);auditRows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,300);window.renderUserAudit();if(show)showToast('Historial actualizado.')}catch(e){box.innerHTML=`<div class="audit-empty">No se pudo cargar el historial: ${esc(e.message)}</div>`}finally{auditLoading=false}};
window.renderUserAudit=function(){const box=$('#userAuditList');if(!box)return;const term=($('#auditSearch')?.value||'').toLowerCase(),act=$('#auditActionFilter')?.value||'';const rows=auditRows.filter(r=>(!act||r.action===act)&&(!term||[r.targetName,r.targetEmail,r.actorEmail,r.reason].join(' ').toLowerCase().includes(term)));box.innerHTML=rows.length?rows.map(r=>`<article class="audit-item"><div class="audit-date">${new Date(r.createdAt).toLocaleString('es-PE')}</div><div class="audit-detail"><b>${esc(r.targetName||r.targetEmail||'Usuario')}</b><p>Realizado por ${esc(r.actorEmail||r.actorUid||'Administrador')} · Motivo: ${esc(r.reason||'-')}</p><div class="audit-changes">${(r.changes||[]).map(esc).join(' · ')}</div></div><span class="audit-action">${esc(r.action)}</span></article>`).join(''):'<div class="audit-empty">No hay cambios que coincidan con el filtro.</div>'};
function hook(){
 const tab=document.querySelector('#adminMenu button[data-view="users"]');
 if(tab&&!tab.dataset.auditHook){tab.dataset.auditHook='1';tab.addEventListener('click',()=>setTimeout(()=>window.loadUserAudit(false),350))}
}
document.addEventListener('DOMContentLoaded',()=>{hook();setTimeout(hook,500)});
})();
